export const FIND_USER_PROFILE_REQUEST = 'FIND_USER_PROFILE_REQUEST';
export const FIND_USER_PROFILE_SUCCESS = 'FIND_USER_PROFILE_SUCCESS';
export const FIND_USER_PROFILE_FAILURE = 'FIND_USER_PROFILE_FAILURE';
